### ISSUE TITLE
Deadlock on main thread

### ISSUE THREAD

**Issue by edenman** [SiftScience/sift-ios#71] opened 2018-03-08 22:53 UTC
It looks like SFCollectIosDeviceProperties is trying to fork a new thread and it hangs.  Sift 0.9.11 in a dev build, but I've only seen it happen a couple of times.  Here's the relevant threads:

![screen shot 2018-03-08 at 2 51 13 pm](https://user-images.githubusercontent.com/1063557/37181038-3fe06ed4-22e0-11e8-9e48-eeb6b02ee5bc.png)

**Comment by quanpod** [comment] 2018-03-08 23:02
Acknowledging @edenman, thanks for the report - @garylee1 to take a look.

**Comment by quanpod** [comment] 2018-03-23 21:46
Updating @edenman - @garylee1 has primarily been focused on a big Android release update.  Will have more details next week when he's back in the office.

**Comment by ajeenkya** [comment] 2018-06-13 19:30
@garylee1 Has this issue been resolved?

**Comment by dfed** [comment] 2018-06-13 19:35
Looks like the hang is being caused by `fork()`, which is being used to determine if the current device is jailbroken. A little bit of digging around the repos that have jailbreak detection makes me think there are likely significantly lighter-weight ways to detect if a device is jailbroken. Any chance we can replace the `fork()` call with something a little less extreme?

**Comment by garylee1** [comment] 2018-06-13 19:43
thanks for your patience everyone – i arrived at the same conclusion as @dfed and i will look into a simpler solution for our next release.

**Comment by edenman** [comment] 2018-06-13 21:48
(I haven't seen this lately, fwiw)

**Comment by garylee1** [comment] 2018-07-17 22:02
Hey everybody – thanks for your patience. This has been fixed and released with https://github.com/SiftScience/sift-ios/releases/tag/v1.0.1 – we believe that the jailbroken detection is still equally effective without the `fork()` call.

**Closed by garylee1** 2018-07-17 22:02 UTC
